// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20240911144649_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Data.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Content = "When you need to add or remove elements frequently, a LinkedList is the better choice. When you need to access elements by index, a List is the better choice.",
                            Title = "When to use a List vs a LinkedList"
                        },
                        new
                        {
                            ID = 2,
                            Content = "Continuous integration and continuous deployment (CI/CD) pipelines are essential for agile software development because they automate the process of building, testing, and deploying software. This allows developers to quickly and easily deliver new features and updates to customers.",
                            Title = "Why CI/CD Pipelines Are Essential for Agile Software Development"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
